export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>LW App</title>
  <base href="/travel-app/">
  <meta name="viewport" content="width=device-width, initial-scale=1">  
<style>.button-primary{height:49px;width:auto;border-radius:25px;border-width:1px;cursor:pointer;font-size:var(--font-size-m);font-weight:var(--font-weight-extra-bold);padding:12px 25px;color:var(--white-color);background-color:var(--primary-color);border-color:var(--primary-color)}.button-primary:hover{background-color:var(--secondary-color);border-color:var(--secondary-color)}.button-primary:active{background-color:var(--primary-color);border-color:var(--primary-color)}.button-primary:disabled{background-color:var(--grey-dark);border-color:var(--grey-dark)}html,body{width:100%;height:100%;background-color:var(--grey-dark);margin:0;font-family:FiraCode}:root{--bg-color: #eceefe;--white-color: #fff;--black-color: #000;--grey-dark: #4a4a4a;--primary-color: #0d6efd;--secondary-color: #6c757d;--hoverIdee-color: #ede616}@font-face{font-family:FiraCode;src:url("./media/FiraCode-Regular-BF35OYJW.ttf") format("truetype");font-weight:400;font-style:normal}:root{--font-size-error: 14px;--font-size-title-default: 24px;--font-size-s: 16px;--font-size-m: 18px;--font-size-l: 20px;--font-size-ml: 24px;--font-size-xl: 32px;--font-size-xxl: 46px;--font-weight-normal: 400;--font-weight-bold: 500;--font-weight-extra-bold: 700;--font-primary: font-family: "FiraCode"}
</style><link rel="stylesheet" href="styles-XCMTVZAU.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-XCMTVZAU.css"></noscript><style ng-app-id="ng">.start-app[_ngcontent-ng-c694846876]{height:100vh;display:flex;justify-content:center;align-items:center}.start-Animation-img[_ngcontent-ng-c694846876]{width:200px;height:200px}.start-Animation-img[_ngcontent-ng-c694846876]   img[_ngcontent-ng-c694846876]{width:200px;height:200px;animation:_ngcontent-ng-c694846876_animation 2s linear infinite;object-fit:cover}.start-Animation[_ngcontent-ng-c694846876]{width:100%;display:flex;justify-content:center;align-items:center;flex-wrap:wrap;gap:20px}.start-Animation-text[_ngcontent-ng-c694846876]{height:60px;display:flex;justify-content:center;align-items:center;font-size:var(--font-size-xl);color:var(--white-color);text-align:center}.animation-text[_ngcontent-ng-c694846876]{width:50ch;animation:_ngcontent-ng-c694846876_tippen 2s steps(15);white-space:nowrap;overflow:hidden}@keyframes _ngcontent-ng-c694846876_tippen{0%{width:0}}@keyframes _ngcontent-ng-c694846876_animation{0%{transform:rotate(0)}to{transform:rotate(360deg)}}@media (max-width: 1200px){.start-Animation[_ngcontent-ng-c694846876]{flex-direction:column}}</style><style ng-app-id="ng">.start[_ngcontent-ng-c2911919129]{width:100%;height:100vh;display:flex;justify-content:center;align-items:center}.start-content[_ngcontent-ng-c2911919129]{width:500px;height:400px;border:1px solid var(--grey-dark);background-color:var(--black-color);border-radius:30px;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:50px;color:var(--white-color)}.loading[_ngcontent-ng-c2911919129]{width:100%;height:100%;display:flex;justify-content:center;align-items:center}.loading-content[_ngcontent-ng-c2911919129]{width:200px;height:100px;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:20px}.loading-img[_ngcontent-ng-c2911919129]{width:50px;height:50px;background-color:var(--white-color);border:1px solid var(--grey-dark);border-radius:30px;display:flex;justify-content:center;align-items:center;animation:_ngcontent-ng-c2911919129_starts 2s ease-in-out infinite}.loading-img[_ngcontent-ng-c2911919129]   img[_ngcontent-ng-c2911919129]{width:50px;height:50px}@keyframes _ngcontent-ng-c2911919129_starts{0%{transform:rotate(0)}to{transform:rotate(180deg)}}</style></head>
<body>
  <app-root ng-version="19.2.14" _nghost-ng-c694846876 ng-server-context="ssg"><!----><router-outlet _ngcontent-ng-c694846876></router-outlet><app-start _nghost-ng-c2911919129><section _ngcontent-ng-c2911919129 class="start"><div _ngcontent-ng-c2911919129 class="start-content"><!----><span _ngcontent-ng-c2911919129>Willkommen auf der Länder- und Wetter-App</span><button _ngcontent-ng-c2911919129 class="button-primary">Los geht's</button><!----></div></section></app-start><!----><!----></app-root>
<link rel="modulepreload" href="chunk-4CLCTAJ7.js"><script src="polyfills-B6TNHZQ6.js" type="module"></script><script src="main-WKBZ5A5Q.js" type="module"></script>

</body></html>`;